#!/bin/sh

## live-tools(7) - System Support Scripts
## Copyright (C) 2013 Richard Nelson <unixabg@gmail.com>
## Copyright (C) 2013 Daniel Baumann <mail@daniel-baumann.ch>
##
## This program comes with ABSOLUTELY NO WARRANTY; for details see COPYING.
## This is free software, and you are welcome to redistribute it
## under certain conditions; see COPYING for details.


set -e

_URL="install.live-systems.org::files/FIXME/PATH_TO_FILES/"

_TARGET="/dev/sda"

# Dependencies
if [ ! -e /sbin/parted ]
then
	echo "E: /sbin/parted - no such file"
	echo "E: On Debian based systems, parted can be installed with:"
	echo "E:   apt-get install parted"

	exit 1
fi

if [ ! -e /usr/bin/extlinux ]
then
	echo "E: /usr/bin/extlinux - no such file"
	echo "E: On Debian based systems, extlinux can be installed with:"
	echo "E:   apt-get install extlinux"

	exit 1
fi

if [ ! -e /usr/bin/rsync ]
then
	echo "E: /usr/bin/rsync - no such file"
	echo "E: On Debian based systems, rsync can be installed with:"
	echo "E:   apt-get install rsync"

	exit 1
fi

# Display warning
cat << EOF
######################################################
WARNING: This will erase all data on the target device
######################################################

Please enter URL to download the ${_IMAGE_FILE} image from
(default: ${_URL})
EOF

# Ask for URL
echo -n ": "
read _READ

_URL="${_READ:-${_URL}}"

# Display partitions
cat << EOF

-------------------------------------------------------------------------------
$(blkid | sort)
-------------------------------------------------------------------------------

EOF

# Ask for target device
echo -n "Please enter block device to install system to (default: ${_TARGET}): "
read _READ

_TARGET="${_READ:-${_TARGET}}"

if [ ! -b "${_TARGET}" ]
then
	echo "E: ${_TARGET} not a block device, aborting."
	exit 1
fi

cat << EOF

#########################################################
WARNING: This will erase all data on the ${_TARGET} device
#########################################################

You are about to do something potentially harmful.
To continue type in the phrase 'Yes, do as I say!'
EOF

echo -n ": "
read _CONTINUE

case "${_CONTINUE}" in
	'Yes, do as I say!')

		;;

	*)
		echo "Abort."

		exit 1
		;;
esac

# Zero fill just a bit
echo "Starting dd command for short zero fill..."
dd if=/dev/zero of=${_TARGET} bs=1024 count=1024

# Make a partitions
echo "Starting parted command to make lablel and partition..."

# Primary Firmware partition
#parted -s -a optimal ${_TARGET} mklabel msdos -- mkpart primary ext4 1 -1
parted -s -a optimal ${_TARGET} mklabel msdos -- mkpart primary ext4 1 10000
parted -s -a optimal ${_TARGET} -- mkpart primary linux-swap 10000 12000

# Set the block device to boot.
echo "Starting parted command to enable boot..."
parted -s ${_TARGET} --  set 1 boot on
parted -s ${_TARGET} -- print

#READ _PAUSE

# Make new filesystem on the new partitions.
echo "Making filesystem..."
mkfs.ext4 -L Firmware ${_TARGET}1

# Mount the target filesystem
echo "Mounting file system to allow saving of webboot files..."
mount ${_TARGET}1 /mnt

# Download the webboot files from server
echo "Downloading webboot files..."

# Rsync the files to the target machine.
rsync -av --progress ${_URL}/live /mnt/

# Download the boot and menu files from server
echo "Downloading boot and menu files..."

# Rsync the files to the target machine.
rsync -av --progress ${_URL}/boot /mnt/

# Writing mbr
# FIXME: needs update for syslinux 6.0
dd if=/usr/lib/extlinux/mbr.bin of="${_TARGET}" bs=440 count=1 conv=notrunc

# Writing bootloader
extlinux --install /mnt/boot/extlinux

# Sync and umount
echo "Cleanup of firmware layer with sync and umount..."
umount /mnt
sync

echo "Please halt your machine and boot up to your live firmware."
